#######################################################################
# Ping Identity DevOps Chart
########################################################################
apiVersion: v2
name: ping-devops
########################################################################
# 0.5.2 - Refer to http://helm.pingidentity.com/release-notes/#release-052
########################################################################
version: 0.5.2
description: All Ping Identity product images with integration
type: application
home: https://devops.pingidentity.com/
appVersion: "2101"
