{{- include "pinglib.configmap" (list . "pingdataconsole") -}}



{{- define "pingdataconsole.configmap" -}}
{{- $top := index . 0 -}}
{{- $v := index . 1 -}}
data:
  LDAPS_PORT: {{ $top.Values.pingdirectory.services.ldaps.containerPort | quote }}
  ROOT_USER: {{ $v.defaultLogin.username | quote }}
{{- end -}}